name: Build and Deploy JAR Applications

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Build project with Maven
        run: mvn clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Set up SSH private key
        run: echo "${{secrets.AZURE_SSH_KEY}}" > $GITHUB_WORKSPACE/azure_key.pem

      - name: Set permissions on the SSH key
        run: chmod 600 $GITHUB_WORKSPACE/azure_key.pem

      - name: Test SSH connection to VM
        run: |
          echo "Testing SSH connection to VM:"
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'echo "SSH connection successful!"'
      - name: List JAR files found
        run: |
          echo "Listing all JAR files found:"
          find . -name "*.jar"
      - name: Deploy and start applications
        run: |
          modules=("User" "Course" "Exam" "Question" "Intake")
          
          for module in "${modules[@]}"; do
            JAR_PATH="./$module/target/$module-0.0.1-SNAPSHOT.jar"
            echo "Deploying $module JAR to VM..."
          
            scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem $JAR_PATH azureuser@${{ secrets.AZURE_VM_IP }}:/home/azureuser/
          
            echo "Starting $module application on VM..."
            ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{ secrets.AZURE_VM_IP }} \
              "nohup java -jar /home/azureuser/$(basename $JAR_PATH) > /dev/null 2>&1 &"
          
            sleep 10
          done