name: Build and deploy JAR app - galaxys24ultra

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Build project with Maven
        run: mvn clean package

      - name: List target directory
        run: |
          echo "Listing target directory:"
          ls -la **/target/*.jar
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-artifacts
          path: '**/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Set up SSH private key
        run: echo "${{secrets.AZURE_SSH_KEY}}" > $GITHUB_WORKSPACE/azure_key.pem

      - name: Set permissions on the SSH key
        run: chmod 600 $GITHUB_WORKSPACE/azure_key.pem

      - name: Test SSH connection to VM
        run: |
          echo "Testing SSH connection to VM:"
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'echo "SSH connection successful!"'
      - name: List JAR files found
        run: |
          echo "Listing all JAR files found:"
          find . -name "*.jar"
          

      - name: Copy User JAR to VM
        run: scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem ./User/target/User-0.0.1-SNAPSHOT.jar azureuser@${{secrets.AZURE_VM_IP}}:/home/azureuser/

      - name: Start User application on VM
        run: |
          echo "Starting User application on VM..."
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'nohup java -jar /home/azureuser/User-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &'
      - name: Wait for User app to start
        run: sleep 10

      - name: Copy Course JAR to VM
        run: scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem ./Course/target/Course-0.0.1-SNAPSHOT.jar azureuser@${{secrets.AZURE_VM_IP}}:/home/azureuser/

      - name: Start Course application on VM
        run: |
          echo "Starting Course application on VM..."
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'nohup java -jar /home/azureuser/Course-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &'
      - name: Wait for Course app to start
        run: sleep 10

      - name: Copy Exam JAR to VM
        run: scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem ./Exam/target/Exam-0.0.1-SNAPSHOT.jar azureuser@${{secrets.AZURE_VM_IP}}:/home/azureuser/

      - name: Start Exam application on VM
        run: |
          echo "Starting Exam application on VM..."
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'nohup java -jar /home/azureuser/Exam-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &'
      - name: Wait for Exam app to start
        run: sleep 10

      - name: Copy Question JAR to VM
        run: scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem ./Question/target/Question-0.0.1-SNAPSHOT.jar azureuser@${{secrets.AZURE_VM_IP}}:/home/azureuser/

      - name: Start Question application on VM
        run: |
          echo "Starting Question application on VM..."
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'nohup java -jar /home/azureuser/Question-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &'
      - name: Wait for Question app to start
        run: sleep 10

      - name: Copy Intake JAR to VM
        run: scp -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem ./Intake/target/Intake-0.0.1-SNAPSHOT.jar azureuser@${{secrets.AZURE_VM_IP}}:/home/azureuser/

      - name: Start Intake application on VM
        run: |
          echo "Starting Intake application on VM..."
          ssh -o StrictHostKeyChecking=no -i $GITHUB_WORKSPACE/azure_key.pem azureuser@${{secrets.AZURE_VM_IP}} 'nohup java -jar /home/azureuser/Intake-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &'
      - name: Wait for Intake app to start
        run: sleep 10